production:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: lostcityoftrellech.co.uk_production
    pool: 5
    username: rails_app
    password: <%= ENV['RAILS_DB_PWD'] %>
    host: localhost 
