production:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: rswilson.com_production
    pool: 5
    username: rails_app
    password: <%= ENV['RAILS_DB_PWD'] %>
    host: localhost
